// <auto-generated />
#nullable disable

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace IAVH.BioTablero.CM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GeneralContext))]
    [Migration("20250919140408_AddInitiativeJoinInvitations")]
    partial class AddInitiativeJoinInvitations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("creator_user_name");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<string>("Message")
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("join_invitation", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitationGuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int>("JoinInvitationId")
                        .HasColumnType("integer")
                        .HasColumnName("join_invitation_id");

                    b.HasKey("Id");

                    b.HasIndex("JoinInvitationId", "Email")
                        .IsUnique();

                    b.ToTable("join_invitation_guest", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitation", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("JoinInvitations")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitationGuest", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitation", "JoinInvitation")
                        .WithMany("Guests")
                        .HasForeignKey("JoinInvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JoinInvitation");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", b =>
                {
                    b.Navigation("JoinInvitations");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitation", b =>
                {
                    b.Navigation("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
