// <auto-generated />
using System;
using IAVH.BioTablero.CM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IAVH.BioTablero.CM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GeneralContext))]
    [Migration("20250120000000_AddPolygonAreaToInitiative")]
    partial class AddPolygonAreaToInitiative
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This migration only adds a column, so we don't need to rebuild the entire model
            // The model will be updated when the next full migration is generated
#pragma warning restore 612, 618
        }
    }
}

