// <auto-generated />
using System;

using IAVH.BioTablero.CM.Infrastructure.Persistence;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using NetTopologySuite.Geometries;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IAVH.BioTablero.CM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GeneralContext))]
    [Migration("20260414232803_AddNotifications")]
    partial class AddNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("location", "geo");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.LocationPolygon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon, 4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("GeometrySimplified")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("geometry_simplified");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("location_polygon", "geo");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerUrl")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("banner_url");

                    b.Property<string>("Baseline")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("baseline");

                    b.Property<Point>("Coordinate")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("coordinate");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Objective")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("objective");

                    b.Property<Geometry>("Polygon")
                        .HasColumnType("geometry(Polygon, 4326)")
                        .HasColumnName("polygon");

                    b.Property<double>("PolygonArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("polygon_area");

                    b.Property<string>("ShortName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("short_name");

                    b.HasKey("Id");

                    b.ToTable("initiative", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId", "Email")
                        .IsUnique();

                    b.HasIndex("InitiativeId", "Phone")
                        .IsUnique();

                    b.ToTable("initiative_contact", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<string>("Locality")
                        .HasColumnType("text")
                        .HasColumnName("locality");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("InitiativeId", "LocationId", "Locality")
                        .IsUnique();

                    b.ToTable("initiative_location", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("InitiativeId", "TagId")
                        .IsUnique();

                    b.ToTable("initiative_tag", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FocusArea")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("focus_area");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_user_level_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserName", "InitiativeId")
                        .IsUnique();

                    b.ToTable("initiative_user", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeUserLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("initiative_user_level", "initiatives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Leader"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Collaborator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Reader"
                        });
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("creator_user_name");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<string>("Message")
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("join_invitation", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitationGuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int>("JoinInvitationId")
                        .HasColumnType("integer")
                        .HasColumnName("join_invitation_id");

                    b.HasKey("Id");

                    b.HasIndex("JoinInvitationId", "Email")
                        .IsUnique();

                    b.ToTable("join_invitation_guest", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<int?>("LevelId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_user_level_id");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("response_date");

                    b.Property<string>("ReviewerUserName")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("reviewer_user_name");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("join_request_status_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("LevelId");

                    b.HasIndex("StatusId");

                    b.ToTable("join_request", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinRequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("join_request_status", "initiatives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "UnderReview"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Logging.LogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientAgent")
                        .HasColumnType("text")
                        .HasColumnName("client_agent");

                    b.Property<string>("ClientIp")
                        .HasColumnType("text")
                        .HasColumnName("client_ip");

                    b.Property<bool>("CustomRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("custom_record");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("ShortMessage")
                        .HasColumnType("text")
                        .HasColumnName("short_message");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("type");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("logs", "logs");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Notifications.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<DateTime?>("ReadingDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reading_date");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("receiver");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.ToTable("notification", "notifications");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<bool>("IsDraft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_draft");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("publication_date");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_type_id");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("resource", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "Url")
                        .IsUnique();

                    b.ToTable("resource_file", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "UserName")
                        .IsUnique();

                    b.ToTable("resource_like", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "Url")
                        .IsUnique();

                    b.ToTable("resource_link", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("ResourceId", "TagId")
                        .IsUnique();

                    b.ToTable("resource_tag", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("resource_type", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name", "CategoryId")
                        .IsUnique();

                    b.ToTable("tag", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.TagCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tag_category", "initiatives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PoliticalContext"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SocialContext"
                        },
                        new
                        {
                            Id = 3,
                            Name = "BiologicalGroup"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ecosystem"
                        });
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorUserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("author_user_name");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<bool>("FeaturedContent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("featured_content");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<string>("Keywords")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("keywords");

                    b.Property<bool>("Restricted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("restricted");

                    b.Property<string>("Text")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("territory_story", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStoryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("FeaturedContent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("featured_content");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("file_url");

                    b.Property<int>("TerritoryStoryId")
                        .HasColumnType("integer")
                        .HasColumnName("territory_story_id");

                    b.HasKey("Id");

                    b.HasIndex("FileUrl")
                        .IsUnique();

                    b.HasIndex("TerritoryStoryId");

                    b.ToTable("territory_story_image", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStoryLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("TerritoryStoryId")
                        .HasColumnType("integer")
                        .HasColumnName("territory_story_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("TerritoryStoryId", "UserName")
                        .IsUnique();

                    b.ToTable("territory_story_like", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStoryVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("file_url");

                    b.Property<int>("TerritoryStoryId")
                        .HasColumnType("integer")
                        .HasColumnName("territory_story_id");

                    b.HasKey("Id");

                    b.HasIndex("TerritoryStoryId", "FileUrl")
                        .IsUnique();

                    b.ToTable("territory_story_video", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.Location", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.Location", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.LocationPolygon", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.Location", "Location")
                        .WithOne("LocationPolygon")
                        .HasForeignKey("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.LocationPolygon", "LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeContact", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("InitiativeContacts")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeLocation", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("InitiativeLocations")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.Location", "Location")
                        .WithMany("InitiativeLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeTag", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("InitiativeTags")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.Tag", "Tag")
                        .WithMany("TagInitiatives")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeUser", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("InitiativeUsers")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeUserLevel", "Level")
                        .WithMany("InitiativeUsers")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitation", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("JoinInvitations")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitationGuest", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitation", "JoinInvitation")
                        .WithMany("Guests")
                        .HasForeignKey("JoinInvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JoinInvitation");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinRequest", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("JoinRequests")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeUserLevel", "Level")
                        .WithMany("JoinRequests")
                        .HasForeignKey("LevelId");

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinRequestStatus", "Status")
                        .WithMany("JoinRequests")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Level");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.Resource", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("Resources")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceType", "ResourceType")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceFile", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.Resource", "Resource")
                        .WithMany("Files")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceLike", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.Resource", "Resource")
                        .WithMany("Likes")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceLink", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.Resource", "Resource")
                        .WithMany("Links")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceTag", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.Resource", "Resource")
                        .WithMany("ResourceTags")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.Tag", "Tag")
                        .WithMany("TagResources")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.Tag", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.TagCategory", "Category")
                        .WithMany("Tags")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStory", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("TerritoryStories")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStoryImage", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStory", "TerritoryStory")
                        .WithMany("Images")
                        .HasForeignKey("TerritoryStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TerritoryStory");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStoryLike", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStory", "TerritoryStory")
                        .WithMany("Likes")
                        .HasForeignKey("TerritoryStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TerritoryStory");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStoryVideo", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStory", "TerritoryStory")
                        .WithMany("Videos")
                        .HasForeignKey("TerritoryStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TerritoryStory");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.Location", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("InitiativeLocations");

                    b.Navigation("LocationPolygon");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", b =>
                {
                    b.Navigation("InitiativeContacts");

                    b.Navigation("InitiativeLocations");

                    b.Navigation("InitiativeTags");

                    b.Navigation("InitiativeUsers");

                    b.Navigation("JoinInvitations");

                    b.Navigation("JoinRequests");

                    b.Navigation("Resources");

                    b.Navigation("TerritoryStories");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeUserLevel", b =>
                {
                    b.Navigation("InitiativeUsers");

                    b.Navigation("JoinRequests");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitation", b =>
                {
                    b.Navigation("Guests");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinRequestStatus", b =>
                {
                    b.Navigation("JoinRequests");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.Resource", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Likes");

                    b.Navigation("Links");

                    b.Navigation("ResourceTags");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceType", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.Tag", b =>
                {
                    b.Navigation("TagInitiatives");

                    b.Navigation("TagResources");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.TagCategory", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStory", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Likes");

                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
