// <auto-generated />
using System;
using IAVH.BioTablero.CM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IAVH.BioTablero.CM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GeneralContext))]
    partial class GeneralContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<byte>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("location", "geo", t =>
                        {
                            t.HasCheckConstraint("CK_Location_Level_ValidValues", "\"level\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.LocationPolygon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon, 4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("GeometrySimplified")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("geometry_simplified");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("location_polygon", "geo");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.ToTable("category", "indicators");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.Indicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IndicatorTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("indicator_type_id");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.HasKey("Id");

                    b.HasIndex("IndicatorTypeId");

                    b.HasIndex("InitiativeId");

                    b.ToTable("indicator", "indicators");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("IndicatorVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("indicator_version_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IndicatorVersionId", "CategoryId")
                        .IsUnique();

                    b.ToTable("indicator_group", "indicators");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IndicatorId")
                        .HasColumnType("integer")
                        .HasColumnName("indicator_id");

                    b.Property<string>("Locality")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("locality");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("IndicatorId", "LocationId", "Locality")
                        .IsUnique();

                    b.ToTable("indicator_location", "indicators");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IndicatorId")
                        .HasColumnType("integer")
                        .HasColumnName("indicator_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("IndicatorId", "TagId")
                        .IsUnique();

                    b.ToTable("indicator_tag", "indicators");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("indicator_type", "indicators");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset?>("DateEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_end");

                    b.Property<int>("IndicatorGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("indicator_group_id");

                    b.Property<float?>("LowerLimit")
                        .HasColumnType("real")
                        .HasColumnName("lower_limit");

                    b.Property<int>("MeasureUnitId")
                        .HasColumnType("integer")
                        .HasColumnName("measure_unit_id");

                    b.Property<float?>("UpperLimit")
                        .HasColumnType("real")
                        .HasColumnName("upper_limit");

                    b.Property<float>("Value")
                        .HasColumnType("real")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("IndicatorGroupId");

                    b.HasIndex("MeasureUnitId");

                    b.ToTable("indicator_value", "indicators");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Authorship")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("authorship");

                    b.Property<string>("Considerations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("considerations");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("IndicatorId")
                        .HasColumnType("integer")
                        .HasColumnName("indicator_id");

                    b.Property<string>("Interpretation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("interpretation");

                    b.Property<string>("Methodology")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("methodology");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("IndicatorId", "Version")
                        .IsUnique();

                    b.ToTable("indicator_version", "indicators");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorVersionMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<int>("IndicatorVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("indicator_version_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("IndicatorVersionId", "Title")
                        .IsUnique();

                    b.ToTable("indicator_version_map", "indicators");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.MapLegend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IndicatorVersionMapId")
                        .HasColumnType("integer")
                        .HasColumnName("indicator_version_map_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("IndicatorVersionMapId", "Title")
                        .IsUnique();

                    b.ToTable("map_legend", "indicators");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.MapLegendItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("color_code");

                    b.Property<int>("MapLegendId")
                        .HasColumnType("integer")
                        .HasColumnName("map_legend_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("MapLegendId", "ColorCode")
                        .IsUnique();

                    b.ToTable("map_legend_item", "indicators");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.MeasureUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("name");

                    b.Property<string>("Representation")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("representation");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("measure_unit", "indicators");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerUrl")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("banner_url");

                    b.Property<string>("Baseline")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("baseline");

                    b.Property<Point>("Coordinate")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("coordinate");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("image_url");

                    b.Property<int>("MainLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("main_location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Objective")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("objective");

                    b.Property<Geometry>("Polygon")
                        .HasColumnType("geometry(Polygon, 4326)")
                        .HasColumnName("polygon");

                    b.Property<double>("PolygonArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("polygon_area");

                    b.Property<string>("ShortName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("short_name");

                    b.HasKey("Id");

                    b.HasIndex("MainLocationId");

                    b.ToTable("initiative", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId", "Email")
                        .IsUnique();

                    b.HasIndex("InitiativeId", "Phone")
                        .IsUnique();

                    b.ToTable("initiative_contact", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<string>("Locality")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("locality");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("InitiativeId", "LocationId", "Locality")
                        .IsUnique();

                    b.ToTable("initiative_location", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("InitiativeId", "TagId")
                        .IsUnique();

                    b.ToTable("initiative_tag", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FocusArea")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("focus_area");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_user_level_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserName", "InitiativeId")
                        .IsUnique();

                    b.ToTable("initiative_user", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeUserLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("initiative_user_level", "initiatives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Leader"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Collaborator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Reader"
                        });
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("creator_user_name");

                    b.Property<string>("HtmlMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_message");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<string>("Message")
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("join_invitation", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitationGuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int>("JoinInvitationId")
                        .HasColumnType("integer")
                        .HasColumnName("join_invitation_id");

                    b.HasKey("Id");

                    b.HasIndex("JoinInvitationId", "Email")
                        .IsUnique();

                    b.ToTable("join_invitation_guest", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<int?>("LevelId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_user_level_id");

                    b.Property<DateTimeOffset?>("ResponseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_date");

                    b.Property<string>("ReviewerUserName")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("reviewer_user_name");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("join_request_status_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("LevelId");

                    b.HasIndex("StatusId");

                    b.ToTable("join_request", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinRequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("join_request_status", "initiatives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "UnderReview"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.MonitoringEvents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId", "Date")
                        .IsUnique();

                    b.ToTable("monitoring_events", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Logging.LogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientAgent")
                        .HasColumnType("text")
                        .HasColumnName("client_agent");

                    b.Property<string>("ClientIp")
                        .HasColumnType("text")
                        .HasColumnName("client_ip");

                    b.Property<bool>("CustomRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("custom_record");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("ShortMessage")
                        .HasColumnType("text")
                        .HasColumnName("short_message");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("type");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("logs", "logs");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Notifications.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<DateTimeOffset?>("ReadingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reading_date");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("receiver");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.ToTable("notification", "notifications");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorUserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("author_user_name");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<bool>("IsDraft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_draft");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PublicationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publication_date");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_type_id");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("resource", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "Url")
                        .IsUnique();

                    b.ToTable("resource_file", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "UserName")
                        .IsUnique();

                    b.ToTable("resource_like", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "Url")
                        .IsUnique();

                    b.ToTable("resource_link", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("ResourceId", "TagId")
                        .IsUnique();

                    b.ToTable("resource_tag", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("resource_type", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name", "CategoryId")
                        .IsUnique();

                    b.ToTable("tag", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.TagCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tag_category", "initiatives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PoliticalContext"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SocialContext"
                        },
                        new
                        {
                            Id = 3,
                            Name = "BiologicalGroup"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ecosystem"
                        });
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorUserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("author_user_name");

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<bool>("FeaturedContent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("featured_content");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_id");

                    b.Property<string>("Keywords")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("keywords");

                    b.Property<bool>("Restricted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("restricted");

                    b.Property<string>("Text")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("territory_story", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStoryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("FeaturedContent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("featured_content");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("file_url");

                    b.Property<int>("TerritoryStoryId")
                        .HasColumnType("integer")
                        .HasColumnName("territory_story_id");

                    b.HasKey("Id");

                    b.HasIndex("FileUrl")
                        .IsUnique();

                    b.HasIndex("TerritoryStoryId");

                    b.ToTable("territory_story_image", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStoryLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("TerritoryStoryId")
                        .HasColumnType("integer")
                        .HasColumnName("territory_story_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("TerritoryStoryId", "UserName")
                        .IsUnique();

                    b.ToTable("territory_story_like", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStoryVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("file_url");

                    b.Property<int>("TerritoryStoryId")
                        .HasColumnType("integer")
                        .HasColumnName("territory_story_id");

                    b.HasKey("Id");

                    b.HasIndex("TerritoryStoryId", "FileUrl")
                        .IsUnique();

                    b.ToTable("territory_story_video", "initiatives");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.Location", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.Location", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.LocationPolygon", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.Location", "Location")
                        .WithOne("LocationPolygon")
                        .HasForeignKey("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.LocationPolygon", "LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.Category", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.Indicator", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorType", "Type")
                        .WithMany("Indicators")
                        .HasForeignKey("IndicatorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("Indicators")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorGroup", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.Category", "Category")
                        .WithMany("IndicatorGroups")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorVersion", "IndicatorVersion")
                        .WithMany("Groups")
                        .HasForeignKey("IndicatorVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("IndicatorVersion");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorLocation", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.Indicator", "Indicator")
                        .WithMany("IndicatorLocations")
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.Location", "Location")
                        .WithMany("IndicatorLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indicator");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorTag", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.Indicator", "Indicator")
                        .WithMany("IndicatorTags")
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.Tag", "Tag")
                        .WithMany("TagIndicators")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indicator");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorValue", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorGroup", "Group")
                        .WithMany("Values")
                        .HasForeignKey("IndicatorGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.MeasureUnit", "MeasureUnit")
                        .WithMany("IndicatorValues")
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("MeasureUnit");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorVersion", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.Indicator", "Indicator")
                        .WithMany("Versions")
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indicator");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorVersionMap", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorVersion", "IndicatorVersion")
                        .WithMany("Maps")
                        .HasForeignKey("IndicatorVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndicatorVersion");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.MapLegend", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorVersionMap", "IndicatorVersionMap")
                        .WithMany("Legends")
                        .HasForeignKey("IndicatorVersionMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndicatorVersionMap");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.MapLegendItem", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.MapLegend", "MapLegend")
                        .WithMany("Items")
                        .HasForeignKey("MapLegendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapLegend");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.Location", "MainLocation")
                        .WithMany("Initiatives")
                        .HasForeignKey("MainLocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MainLocation");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeContact", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("InitiativeContacts")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeLocation", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("InitiativeLocations")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.Location", "Location")
                        .WithMany("InitiativeLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeTag", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("InitiativeTags")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.Tag", "Tag")
                        .WithMany("TagInitiatives")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeUser", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("InitiativeUsers")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeUserLevel", "Level")
                        .WithMany("InitiativeUsers")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitation", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("JoinInvitations")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitationGuest", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitation", "JoinInvitation")
                        .WithMany("Guests")
                        .HasForeignKey("JoinInvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JoinInvitation");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinRequest", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("JoinRequests")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeUserLevel", "Level")
                        .WithMany("JoinRequests")
                        .HasForeignKey("LevelId");

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinRequestStatus", "Status")
                        .WithMany("JoinRequests")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Level");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.MonitoringEvents", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("MonitoringEventsList")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.Resource", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("Resources")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceType", "ResourceType")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceFile", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.Resource", "Resource")
                        .WithMany("Files")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceLike", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.Resource", "Resource")
                        .WithMany("Likes")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceLink", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.Resource", "Resource")
                        .WithMany("Links")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceTag", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.Resource", "Resource")
                        .WithMany("ResourceTags")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.Tag", "Tag")
                        .WithMany("TagResources")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.Tag", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.TagCategory", "Category")
                        .WithMany("Tags")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStory", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", "Initiative")
                        .WithMany("TerritoryStories")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStoryImage", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStory", "TerritoryStory")
                        .WithMany("Images")
                        .HasForeignKey("TerritoryStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TerritoryStory");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStoryLike", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStory", "TerritoryStory")
                        .WithMany("Likes")
                        .HasForeignKey("TerritoryStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TerritoryStory");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStoryVideo", b =>
                {
                    b.HasOne("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStory", "TerritoryStory")
                        .WithMany("Videos")
                        .HasForeignKey("TerritoryStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TerritoryStory");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Geo.Location", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("IndicatorLocations");

                    b.Navigation("InitiativeLocations");

                    b.Navigation("Initiatives");

                    b.Navigation("LocationPolygon");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("IndicatorGroups");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.Indicator", b =>
                {
                    b.Navigation("IndicatorLocations");

                    b.Navigation("IndicatorTags");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorGroup", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorType", b =>
                {
                    b.Navigation("Indicators");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorVersion", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Maps");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.IndicatorVersionMap", b =>
                {
                    b.Navigation("Legends");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.MapLegend", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Indicators.MeasureUnit", b =>
                {
                    b.Navigation("IndicatorValues");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.Initiative", b =>
                {
                    b.Navigation("Indicators");

                    b.Navigation("InitiativeContacts");

                    b.Navigation("InitiativeLocations");

                    b.Navigation("InitiativeTags");

                    b.Navigation("InitiativeUsers");

                    b.Navigation("JoinInvitations");

                    b.Navigation("JoinRequests");

                    b.Navigation("MonitoringEventsList");

                    b.Navigation("Resources");

                    b.Navigation("TerritoryStories");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.InitiativeUserLevel", b =>
                {
                    b.Navigation("InitiativeUsers");

                    b.Navigation("JoinRequests");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinInvitation", b =>
                {
                    b.Navigation("Guests");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Initiatives.JoinRequestStatus", b =>
                {
                    b.Navigation("JoinRequests");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.Resource", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Likes");

                    b.Navigation("Links");

                    b.Navigation("ResourceTags");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Resources.ResourceType", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.Tag", b =>
                {
                    b.Navigation("TagIndicators");

                    b.Navigation("TagInitiatives");

                    b.Navigation("TagResources");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.Tags.TagCategory", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("IAVH.BioTablero.CM.Core.Domain.Entities.TerritoryStories.TerritoryStory", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Likes");

                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
