name: Check .NET code

on:
  pull_request:
    branches:
      - develop

jobs:
  verify-dotnet-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.120'

      - name: Restore dependencies
        run: dotnet restore

      - name: Check code format
        run: dotnet format --verify-no-changes

      - name: Build with warnings as errors
        run: dotnet build --no-incremental -warnaserror
